apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: goapp

images:
- name: goapp
  newName: gabrielesteveslima/argocd
  newTag: 68bf35f4c9c3062a3816c32c2b5135b6e2457d04
