name: CD
on:
  push:
    branches: [master]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: build image and push to docker hub
        uses: docker/build-push-actions@v1.1.0
        with:
          username: gabrielesteveslima
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: gabrielesteveslima/argocd
          tags: ${{ github.sha }}, latest